module.exports = {
  'window.devicePixelRatio'                   : 3.5,
  'window.screen.width'                       : 412,
  'window.screen.height'                      : 732,
  'window.innerWidth'                         : 412,
  'window.innerHeight'                        : 658,
  'window.outerWidth'                         : 412,
  'window.outerHeight'                        : 708,
  'window.navigator.connection.downlink'      : 10,
  'window.navigator.connection.effectiveType' : '4g',
  'window.navigator.connection.rtt'           : 200,
  'window.navigator.appCodeName'              : 'Mozilla',
  'window.navigator.appName'                  : 'NetScape',
  'window.navigator.appVersion'               : '5.0 (Linux; Android 8.0.0; SM-G935K Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.81 Mobile Safari/537.36',
  'window.navigator.deviceMemory'             : 4,
  'window.navigator.hardwareConcurrency'      : 8,
  'window.navigator.platform'                 : 'Linux armv8l',
  'window.navigator.product'                  : 'Gecko',
  'window.navigator.productSub'               : '20030107',
  'window.navigator.userAgent'                : 'Mozilla/5.0 (Linux; Android 8.0.0; SM-G935K Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.81 Mobile Safari/537.36',
  'window.navigator.vendor'                   : 'Google Inc.',
  'window.navigator.vendorSub'                : '',
}